// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { ReactNode } from "react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// type RootLayoutProps = {
//   children: ReactNode;
// };

// export default function RootLayout({ children }: RootLayoutProps) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//         style={{
//           backgroundColor: "#3C0753", // dark purple background
//           minHeight: "100vh",
//           color: "white",
//         }}
//       >
//         <div className="flex h-screen">
//           <aside className="w-20 bg-purple-800 flex flex-col items-center py-6 space-y-6 overflow-y-auto">
//             <button className="p-3 rounded hover:bg-purple-700">🏠</button>
//             <button className="p-3 rounded hover:bg-purple-700">⏰</button>
//             <button className="p-3 rounded hover:bg-purple-700">📊</button>
//             <button className="p-3 rounded hover:bg-purple-700">⚙️</button>
//             <button className="p-3 rounded hover:bg-purple-700">📁</button>
//             <button className="p-3 rounded hover:bg-purple-700">💬</button>
//             <button className="p-3 rounded hover:bg-purple-700">🔔</button>
//           </aside>
//           <main className="flex-1 p-6 overflow-auto">
//             {children}
//           </main>
//         </div>

//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { House, Bell } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          backgroundColor: "#3C0753", // Dark purple for whole page
          minHeight: "100vh",
          margin: 0,
          color: "white",
        }}
      >
        <div className="flex h-screen">
          {/* Sidebar */}
          <aside
            className="w-15 flex flex-col items-center py-6 space-y-6 overflow-y-auto"
            style={{
              backgroundColor: "#3C0753", 
            }}
          >
            <button className="w-12 h-12 flex items-center justify-center rounded transition-all duration-200 hover:backdrop-blur-sm hover:bg-gray-300/30">
              <img
                src="/logo.png"   
                alt="Home"
                className="w-5 h-5"    
              />
            </button>
            <button
              className="w-12 h-12 flex items-center justify-center rounded transition-all duration-200 hover:backdrop-blur-sm hover:bg-gray-300/30"
            >
              <House size={24} className="opacity-80" />
            </button>

            <button
              className="w-12 h-12 flex items-center justify-center rounded transition-all duration-200 hover:backdrop-blur-sm hover:bg-gray-300/30"
            >
              <Bell size={24} className="opacity-80" />
            </button>

          </aside>

          {/* Main content */}
          <main className="flex-1 overflow-auto pt-6 pr-14 pb-6 pl-0" style={{ backgroundColor: "#3C0753" }}>
            {children}
          </main>

        </div>
      </body>
    </html>
  );
}
